Feature/slicejack com
Goran94mkd/HTML-CSS-vezbi pull request #9
Opened 2020-11-10 13:20 UTC by Goran94mkd

2020-11-10 22:19 UTC, dpeshevski requested changes

2020-11-10 22:19 UTC, dpeshevski commented on slicejack-com/sliceback6.css
> +#d {/*flex-grow: 1;*/ align-self: flex-end;}
Не треба да биде во една линија дефинирањето на стилот. Те молам следи ја претходната пракса.

2020-11-10 22:19 UTC, dpeshevski commented on slicejack-com/slicejack4.css
> +#d {order: 2; flex-basis: 250px;}
Секое property во нов ред.

2020-11-12 01:30 UTC, Goran94mkd commented on slicejack-com/sliceback6.css
> +#d {/*flex-grow: 1;*/ align-self: flex-end;}
Корегирано.

2020-11-12 01:30 UTC, Goran94mkd commented on slicejack-com/slicejack4.css
> +#d {order: 2; flex-basis: 250px;}
Корегирано.

2020-11-13 10:23 UTC, dpeshevski approved these changes

2020-11-13 21:11 UTC, merged